### ISSUE TITLE
Getting server error in the module while integration

### ISSUE THREAD

**Issue by beersploit** [CiscoSecurity/tr-05-serverless-urlscanio#38]
We integrated using the provided instructions but getting the below error from SecureX:
There was a server error in the module: {:reason "builtins.OSError", :code 500, :message "Something went wrong."} [500]
 
![image](https://user-images.githubusercontent.com/51427622/107215469-5cee6080-6a31-11eb-92d5-0c93df3df634.png)

**Comment by AnastasiiaRozlyvan** [comment]
Hi, thanks for reporting this issue! To understand the root cause of the error, could you please open to the **Monitoring** tab on your AWS console and click the **View logs in CloudWatch** button. There you can find all the latest log streams. It would help us a lot if you could copy the full message of this error and share with us.

**Comment by beersploit** [comment]
Hello, thanks for looking into this. There are many log groups available, which one needs to be checked?
![image](https://user-images.githubusercontent.com/51427622/107252129-0dbd2580-6a5b-11eb-9245-eacba82a0e71.png)

**Comment by AnastasiiaRozlyvan** [comment]
There must be something like `/aws/lambda/tr-urlscanio-relay-dev`

**Comment by beersploit** [comment]
timestamp | message
-- | --
1612800812363 | START RequestId: 5b3d1834-6248-44aa-9fe6-41a7e0bedd7f Version: $LATEST
1612800812364 | Instancing..
1612800814340 | [ERROR]	2021-02-08T16:13:34.337Z	5b3d1834-6248-44aa-9fe6-41a7e0bedd7f	Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt
1612800814340 | [INFO]	2021-02-08T16:13:34.337Z	5b3d1834-6248-44aa-9fe6-41a7e0bedd7f	34.225.249.84 - - [08/Feb/2021:16:13:34 +0000] "POST /health HTTP/1.1" 500 75 "" "Apache-HttpClient/4.5.9 (Java/11.0.8)" 0/3.823
1612800814340 | END RequestId: 5b3d1834-6248-44aa-9fe6-41a7e0bedd7f
1612800814340 | REPORT RequestId: 5b3d1834-6248-44aa-9fe6-41a7e0bedd7f	Duration: 1977.33 ms	Billed Duration: 1978 ms	Memory Size: 512 MB	Max Memory Used: 85 MB	Init Duration: 823.76 ms
1612800820358 | START RequestId: 7ef12c26-cf47-48de-aac3-b9bd91b0e8e2 Version: $LATEST
1612800820364 | [ERROR]	2021-02-08T16:13:40.364Z	7ef12c26-cf47-48de-aac3-b9bd91b0e8e2	Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt
1612800820364 | [INFO]	2021-02-08T16:13:40.364Z	7ef12c26-cf47-48de-aac3-b9bd91b0e8e2	35.172.5.95 - - [08/Feb/2021:16:13:40 +0000] "POST /health HTTP/1.1" 500 75 "" "Apache-HttpClient/4.5.9 (Java/11.0.8)" 0/2.856
1612800820365 | END RequestId: 7ef12c26-cf47-48de-aac3-b9bd91b0e8e2
1612800820365 | REPORT RequestId: 7ef12c26-cf47-48de-aac3-b9bd91b0e8e2	Duration: 4.76 ms	Billed Duration: 5 ms	Memory Size: 512 MB	Max Memory Used: 85 MB

**Comment by AnastasiiaRozlyvan** [comment]
Thanks, we'll investigate what is causing this error.

**Comment by beersploit** [comment]
Do we have any updates regarding this issue?

**Comment by AnastasiiaRozlyvan** [comment]
We have looked into the issue and seems like some steps might have been taken wrong during installation. We'd recommend re-deploying the module. You could let us know if it helps.

**Comment by AnastasiiaRozlyvan** [comment]
I hope you managed to overcome the problems while deploying the urlscan.io module. But if not, the new cisco hosted modules have already become available. They are now much easier to add to your organization because you don't have to deploy AWS Lambda anymore. The module type links are as follows:

- [US Region](https://securex.us.security.cisco.com/integrations/available/d34a36b5-79a1-45b9-858d-1ac9dfd37d1d)
- [EU Region](https://securex.eu.security.cisco.com/integrations/available/cd1c4556-e2cc-4e2e-869d-9d88a9762c91)
- [APJC Region](https://securex.apjc.security.cisco.com/integrations/available/12d6f290-90ea-46c6-87be-b9c0e9875732)
